# Generated by Django 5.2.15 on 2026-07-13 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailyvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='DailyVisit',
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['user', 'date'], name='visitsession_user_date_idx'),
        ),
    ]
