# Generated by Django 5.2.15 on 2026-07-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_visitsession_delete_dailyvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, help_text='Refreshed from the Google ID token on every Google Sign-In.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google's stable per-account ID ('sub' claim) — the real link to a Google Sign-In identity, since email addresses can change but this doesn't.", max_length=255, null=True, unique=True),
        ),
    ]
