# Generated by Django 5.2.15 on 2026-07-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_google_picture_url_user_google_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateTimeField()),
                ('was_staff', models.BooleanField(default=False)),
                ('was_superuser', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
