# Generated by Django 5.2.15 on 2026-07-16 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_deleteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='150 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, spaces, and @/./+/-/_ are allowed.', regex='^[\\w.@+\\- ]+$')], verbose_name='username'),
        ),
    ]
