# Generated by Django 5.2.15 on 2026-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('philosophy', 'Philosophy'), ('mythology', 'Mythology'), ('godvalley', 'The God Valley')], max_length=20),
        ),
    ]
