# Generated by Django 5.2.15 on 2026-07-07 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_content_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'is_published', '-created_at'], name='content_cat_pub_created_idx'),
        ),
    ]
