# Generated by Django 5.2.15 on 2026-07-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_content_content_cat_pub_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tag', models.CharField(choices=[('announcement', 'Announcement'), ('news', 'News'), ('update', 'Update')], default='news', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-created_at'],
            },
        ),
    ]
