# Generated by Django 5.2.15 on 2026-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='philosophy_topic',
            field=models.CharField(blank=True, choices=[('epistemology', 'Epistemology'), ('political_philosophy', 'Political Philosophy')], help_text='Philosophy sub-category filter. Only meaningful for category=philosophy.', max_length=30, null=True),
        ),
    ]
