# Generated by Django 5.2.15 on 2026-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_remove_philosophy_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/content/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/news/%Y/%m/'),
        ),
    ]
